name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: browniebroke/pre-commit-autoupdate-action@main
      - name: commit
        if: failure()
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN}}
          branch: update/pre-commit-hooks
          title: Fixing black
          commit-message: "chore: fixing black"
          body: Update versions of pre-commit hooks to latest version.
          base: ${{ github.head_ref }}